FROM mcr.microsoft.com/vscode/devcontainers/python:3.8
## VSCODE USER Setup
#RUN adduser vscode
#RUN usermod -aG wheel vscode
#RUN echo '%vscode ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
#USER vscode

